name: Dastardly Scan 

on:
  push:
    branches:
      - main

jobs:
  dastardly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dastardly
        uses: portswigger/dastardly-action@v1
        env:
          BURP_START_URL: 'https://ginandjuice.shop'
